display_name: FastVPN
package_name: FastVPN
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/logo.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev
  - libwebkit2gtk-4.1-0
  - libsoup-3.0-0

keywords:
  - FastVPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: FastVPN

categories:
  - Network

startup_notify: true
